# show git branch in prompt, but only check the HEAD file so it's fast
# this doesn't work for all cases but might be good enough
git_branch_fast() {
  if [[ -f .git/HEAD ]]; then
    local ref
    ref=$(sed 's/^ref: refs\/heads\///' .git/HEAD)
    echo " %F{8}$ref%f"
  fi
}

setopt prompt_subst
PROMPT='%F{14}%n%f %F{241}[%f%~%F{241}]%f$(git_branch_fast)
$ '

# keep command history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
setopt sharehistory
setopt incappendhistory

# enable vim mode
bindkey -v

# fzf shell integration
source <(fzf --zsh)

# immediately run command returned by fzf-history-widget
# https://stackoverflow.com/a/77076793
fzf-and-run-widget() {
  fzf-history-widget
  zle accept-line
}
zle -N fzf-and-run-widget
bindkey '^R' fzf-and-run-widget

# cd setopts
setopt nocaseglob
setopt correct
setopt auto_cd

# aliases
alias ..='cd ..'
alias profile='source /usr/local/bin/aws_profile_fzf.sh'
