PROMPT='%F{14}%n%f %F{241}[%f%~%F{241}]%f
$ '

# keep command history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
setopt sharehistory
setopt incappendhistory

# enable vim mode
bindkey -v

# fzf shell integration
source <(fzf --zsh)

# cd setopts
setopt nocaseglob
setopt correct
setopt auto_cd

# aliases
alias ..='cd ..'
alias profile='source /usr/local/bin/aws_profile_fzf.sh'
